# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_list', models.CharField(choices=[('aerial', 'Aerial'), ('architecture', 'Architecture'), ('landscape', 'Landscape'), ('macro', 'macro'), ('panorama', 'Panorama'), ('portrait', 'Portrait'), ('sports', 'Sports'), ('street', 'Street'), ('wildlife', 'Wildlife')], default='', max_length=14)),
                ('name', models.CharField(default='', max_length=254)),
                ('image', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images')),
                ('description', models.TextField()),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
