# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-30 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_photo_format_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='grid',
            field=models.CharField(choices=[('4', 'Lanscape Mode'), ('2', 'Portrait Mode'), ('8', 'Panorama')], default='', max_length=14),
        ),
    ]
